#!/bin/bash

# ==========================================
# Configuration and initialization
# ==========================================
# Stop immediately on error
set -e

# Color output definitions, to make progress easier to read
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Current date
DATE_TAG=$(date +%y%m%d)

# Base directories
AOSP_ROOT=~/AOSP
ANYKERNEL_ROOT="../anykernel"

# Directory of this script, i.e. the rom_build repository
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Record start time
START_TIME=$(date +%s)

# Helper: print a timestamped status header
print_step() {
    echo -e "\n${BLUE}======================================================${NC}"
    echo -e "${YELLOW}[$(date +%H:%M:%S)] Running: $1${NC}"
    echo -e "${BLUE}======================================================${NC}"
}

# Helper: print elapsed time
print_duration() {
    local END_TIME=$(date +%s)
    local DURATION=$((END_TIME - START_TIME))
    local H=$((DURATION / 3600))
    local M=$(( (DURATION % 3600) / 60 ))
    local S=$((DURATION % 60))
    echo -e "${GREEN}>>> Elapsed time: ${H}h ${M}m ${S}s${NC}"
}

# Helper: merge the update JSON generated by the build (out/) into this repo.
# Build facts come from out/; the metadata fields already present in the repo
# file (maintainer, device, gapps, telegram, dt, ...) are kept as they are.
# Changes are written to the working tree only, never committed.
sync_update_json() {
    local DEVICE=$1
    local OUT_JSON="$AOSP_ROOT/out/target/product/$DEVICE/$DEVICE.json"
    local REPO_JSON="$SCRIPT_DIR/$DEVICE.json"

    if [ ! -f "$OUT_JSON" ]; then
        echo -e "${YELLOW}    - Skipping update JSON sync: $OUT_JSON not found${NC}"
        return 0
    fi

    echo "    - Syncing update JSON -> $SCRIPT_DIR/$DEVICE.json"
    if ! python3 - "$DEVICE" "$OUT_JSON" "$REPO_JSON" <<'PY'
import json, os, re, sys

device, out_path, repo_path = sys.argv[1], sys.argv[2], sys.argv[3]

# Fields produced by the build; every other field is hand-maintained
BUILD_KEYS = [
    "filename", "download", "timestamp", "md5", "sha256",
    "size", "version", "os_patch_level", "os_sdk_level",
]

with open(out_path) as f:
    build = json.load(f)["response"][0]

# Rebuild the download URL from the artifact name:
#   crDroidAndroid-<android>-<date>-<device>-v<version>.zip
#     -> .../releases/download/crDroidAndroid-<android>-<date>-v<version>/<filename>
match = re.match(
    r"^crDroidAndroid-(?P<android>[\d.]+)-(?P<date>\d{8})-.*-v(?P<version>[\d.]+)\.zip$",
    build.get("filename", ""),
)
if match:
    tag = "crDroidAndroid-{android}-{date}-v{version}".format(**match.groupdict())
    build["download"] = "https://github.com/mirukurusan/rom_build/releases/download/{}/{}".format(
        tag, build["filename"]
    )
else:
    print("    - Warning: unrecognized artifact name, keeping the existing download URL")

if os.path.exists(repo_path):
    with open(repo_path) as f:
        repo = json.load(f)
    entry = repo["response"][0]
    # Fields this file does not have yet are inserted right after "version"
    missing = [k for k in BUILD_KEYS if k in build and k not in entry]
    keys = list(entry)
    if missing:
        at = keys.index("version") + 1 if "version" in keys else len(keys)
        keys = keys[:at] + missing + keys[at:]
    merged = {}
    for k in keys:
        if k in missing or (k in BUILD_KEYS and k in build):
            merged[k] = build[k]
        else:
            merged[k] = entry.get(k)
    repo["response"][0] = merged
else:
    # No metadata file yet: create it from the build output, metadata left blank
    repo = {"response": [build]}
    merged = build
    print("    - Note: created {}.json, fill in the metadata fields".format(device))

with open(repo_path, "w") as f:
    json.dump(repo, f, indent=4)
    f.write("\n")

print("    - Synced: {}".format(merged.get("filename", "?")))
PY
    then
        echo -e "${RED}    - Error: failed to sync $DEVICE.json into $SCRIPT_DIR (build continues)${NC}"
    fi
}

# Make sure we are in the AOSP root directory
cd "$AOSP_ROOT"

print_step "Initializing build environment (source build/envsetup.sh)"
source build/envsetup.sh

# ==========================================
# Phase 1: switch kernel branch -> lineage-23.2
# ==========================================

print_step "Phase 1: switching kernel branch -> lineage-23.2"

cd kernel/lge/sdm845
git checkout lineage-23.2
echo "Current kernel Git state:"
git log -1 --oneline
cd ../../..

# ==========================================
# Phase 2: build judyln on the prebuilt-audio branches
# ==========================================

print_step "Phase 2: switching judyln-common branches -> prebuilt-audio and building judyln"

cd device/lge/judyln-common
git checkout lineage-23.2-prebuilt-audio
echo "Current device judyln-common Git state:"
git log -1 --oneline
cd ../../..

cd vendor/lge/judyln-common
git checkout lineage-23.0-prebuilt-audio
echo "Current vendor judyln-common Git state:"
git log -1 --oneline
cd ../../..

breakfast judyln
m bacon -j8
sync_update_json "judyln"
print_duration

# ==========================================
# Phase 3: build judypn
# ==========================================

# 1. judypn
print_step "Phase 3: building judypn ROM (m bacon)"
breakfast judypn
m bacon -j8
sync_update_json "judypn"
print_duration

# ==========================================
# Phase 4: build judyp
# ==========================================

# 2. judyp
print_step "Phase 4: building judyp ROM (m bacon)"
breakfast judyp
m bacon -j8
sync_update_json "judyp"
print_duration

# ==========================================
# Kernel processing function
# ==========================================
process_kernel() {
    local DEVICE=$1
    local VARIANT=$2
    local TARGET_DIR="$ANYKERNEL_ROOT/$DEVICE-$VARIANT"
    local ZIP_NAME="$DEVICE-$VARIANT-$DATE_TAG.zip"

    echo -e "${GREEN}>>> Processing device: $DEVICE ($VARIANT)${NC}"

    # 1. Build bootimage
    echo "    - Configuring breakfast..."
    breakfast "$DEVICE" > /dev/null 2>&1 # Suppress breakfast spam, keep only the m progress output

    echo "    - Building bootimage..."
    m bootimage

    # 2. Define the source file path
    local KERNEL_OBJ="out/target/product/$DEVICE/obj/KERNEL_OBJ/arch/arm64/boot/Image.gz-dtb"

    # 3. Check the directory
    if [ ! -d "$TARGET_DIR" ]; then
        echo -e "${RED}Error: directory $TARGET_DIR does not exist!${NC}"
        exit 1
    fi

    # 4. Copy
    echo "    - Copying kernel file..."
    cp "$KERNEL_OBJ" "$TARGET_DIR/"

    # 5. Package (show the file list being packed, to give a sense of live progress)
    echo "    - Packaging zip..."
    current_dir=$(pwd)
    cd "$TARGET_DIR"
    # Use -r to list the files being compressed, so the user can see progress
    zip -r "../$ZIP_NAME" * -x "*.git*" -x "*.DS_Store*" | grep "adding:" | awk '{printf "."; fflush()}'
    echo "" # newline
    cd "$current_dir"

    echo -e "${GREEN}>>> Done: $ZIP_NAME${NC}"
}

# ==========================================
# Phase 5: kernel branch lineage-23.2-ksun-new
# ==========================================

print_step "Phase 5: switching kernel branch -> lineage-23.2-ksun-new"

cd kernel/lge/sdm845
git checkout lineage-23.2-ksun-new
echo "Current kernel Git state:"
git log -1 --oneline
cd ../../..

process_kernel "judyln" "A16-ksun"
process_kernel "judypn" "A16-ksun"
process_kernel "judyp"  "A16-ksun"
print_duration

# ==========================================
# Phase 6: kernel branch lineage-23.2-ksun-susfs (disabled)
# ==========================================

# print_step "Phase 6: switching kernel branch -> lineage-23.2-ksun-susfs"

# cd kernel/lge/sdm845
# git checkout lineage-23.2-ksun-susfs
# echo "Current kernel Git state:"
# git log -1 --oneline
# cp -r ../kernelsu/* ./KernelSU-Next/kernel/
# cd ../../..

# process_kernel "judyln" "A16-ksun-susfs"
# process_kernel "judypn" "A16-ksun-susfs"
# process_kernel "judyp"  "A16-ksun-susfs"

# ==========================================
# End
# ==========================================
echo -e "\n${GREEN}######################################################${NC}"
echo -e "${GREEN}  All build tasks completed!${NC}"
echo -e "${GREEN}  Output directory: $ANYKERNEL_ROOT${NC}"
echo -e "${GREEN}######################################################${NC}"
print_duration
